name: React CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Step 5: Build React app
      - name: Build
        run: npm run build

      # Step 6: Debug Docker info (ADD THIS HERE)
      - name: Debug Docker info
        run: |
          echo "Docker version:"
          docker version
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"

      # Step 7: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build Docker image
      - name: Build Docker image
        run: docker build -t venkateshsagar/rhello-k8s:v13 .

      # Step 9: Push Docker image
      - name: Push Docker image
        run: docker push venkateshsagar/rhello-k8s:v13
