name: React CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Step 5: Build React app
      - name: Build
        run: npm run build

      # Step 6: Login to Docker Hub **before building image for push**
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build Docker image
      - name: Build Docker image
        run: docker build -t venkateshsagar/hello-k8s:latest .

      # Step 8: Push Docker image
      - name: Push Docker image
        run: docker push venkateshsagar/hello-k8s:latest
